# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pirce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(help_text='\u4ef7\u683c')),
                ('created', models.DateTimeField(auto_now=True, help_text='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.CharField(help_text='\u552f\u4e00\u6807\u8bc6', max_length=100)),
                ('name', models.CharField(help_text='\u540d\u79f0', max_length=1000)),
                ('url', models.CharField(help_text='\u8be6\u60c5\u8fde\u63a5', max_length=1000)),
                ('img', models.CharField(help_text='\u56fe\u7247\u8fde\u63a5', max_length=1000)),
                ('max_price', models.FloatField(default=0, help_text='\u6700\u9ad8\u4ef7\u683c')),
                ('min_price', models.FloatField(default=0, help_text='\u6700\u4f4e\u4ef7\u683c')),
                ('created', models.DateTimeField(auto_now=True, help_text='\u521b\u5efa\u65f6\u95f4')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'ordering': ('-modified',),
            },
        ),
        migrations.AddField(
            model_name='pirce',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.Product'),
        ),
    ]
