# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-11 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pirce',
            new_name='Price',
        ),
    ]
