# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20160711_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.CharField(default='', help_text='\u4f9b\u5e94\u5546', max_length=100),
        ),
    ]
